/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#131e8c',
        'on-secondary-container': '#a7b6cc',
        'secondary-container': '#39485a',
        'secondary': '#b9c8de',
        'on-secondary': '#233143',
        'surface-container-highest': '#303633',
        'on-primary-container': '#00422b',
        'surface-variant': '#303633',
        'outline-variant': 'rgba(60, 74, 66, 0.2)',
        'on-error': '#690005',
        'on-primary-fixed-variant': '#005236',
        'on-tertiary-fixed': '#000767',
        'on-primary': '#003824',
        'inverse-surface': '#dee4e0',
        'secondary-fixed': '#d4e4fa',
        'surface-container-lowest': '#090f0d',
        'on-secondary-fixed-variant': '#39485a',
        'surface': '#0f1512',
        'error': '#ffb4ab',
        'on-primary-fixed': '#002113',
        'tertiary-fixed': '#e0e0ff',
        'primary-fixed-dim': '#4edea3',
        'primary-container': '#10b981',
        'surface-dim': '#08120f',
        'on-tertiary-fixed-variant': '#2f3aa3',
        'tertiary': '#bdc2ff',
        'surface-container-high': '#252b29',
        'tertiary-container': '#909aff',
        'surface-container': '#1b211e',
        'outline': '#86948a',
        'inverse-primary': '#006c49',
        'surface-tint': '#4edea3',
        'on-background': '#dee4e0',
        'primary': '#4edea3',
        'tertiary-fixed-dim': '#bdc2ff',
        'inverse-on-surface': '#2b322f',
        'secondary-fixed-dim': '#b9c8de',
        'on-surface': '#dee4e0',
        'on-error-container': '#ffdad6',
        'background': '#0f1512',
        'on-surface-variant': '#bbcabf',
        'on-secondary-fixed': '#0d1c2d',
        'surface-container-low': '#171d1a',
        'surface-bright': '#343b38',
        'on-tertiary-container': '#1f2994',
        'error-container': '#93000a',
        'primary-fixed': '#6ffbbe',
      },
      fontFamily: {
        'headline': ['Space Grotesk', 'sans-serif'],
        'body': ['Space Grotesk', 'sans-serif'],
        'label': ['Space Grotesk', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
